pull_request_rules:
  - name: Ready to test
    conditions:
      - base=master
      - -title~=(?i)wip
      - label!=work-in-progress
      - -conflict
      - status-success=test
    actions:
      backport:
        branches:
          - review
      merge:
          method: merge
